import http from 'http'; import fs from 'fs';
const t=await new Promise((res,rej)=>{http.get({host:'127.0.0.1',port:9222,path:'/json/list'},r=>{let b='';r.on('data',c=>b+=c);r.on('end',()=>res(JSON.parse(b)));}).on('error',rej);});
const page=t.find(x=>x.type==='page'&&x.webSocketDebuggerUrl&&/index\.html/.test(x.url));
const ws=new WebSocket(page.webSocketDebuggerUrl); await new Promise(r=>ws.onopen=r);
let id=0;const p=new Map();ws.onmessage=e=>{const m=JSON.parse(e.data);if(m.id&&p.has(m.id)){p.get(m.id)(m);p.delete(m.id);}};
const cmd=(m,q={})=>new Promise((res,rej)=>{const i=++id;p.set(i,x=>x.error?rej(new Error(JSON.stringify(x.error))):res(x.result));ws.send(JSON.stringify({id:i,method:m,params:q}));});
const ev=async x=>{const r=await cmd('Runtime.evaluate',{expression:x,awaitPromise:true,returnByValue:true,timeout:60000});if(r.exceptionDetails)throw new Error(r.exceptionDetails.exception?.description||r.exceptionDetails.text);return r.result.value;};
const wait=ms=>new Promise(r=>setTimeout(r,ms));
console.log(await ev(`(function(){ document.querySelectorAll('#compOv').forEach(o=>o.remove()); document.body.classList.remove('composing');
  const nidos=state.media.filter(m=>m.kind==='nest');
  if(!nidos.length)return 'no hay nidos: '+state.media.map(m=>m.kind).join(',');
  const n=nidos[nidos.length-1];
  _previewClock=1.2; render();
  openCompose(null,null,n,null,null);
  const c=document.querySelector('#cMedia');
  return { titulo:document.querySelector('#compOv .t').textContent, enCesta:[...c.querySelectorAll('.cbname')].map(e=>e.textContent).length }; })()`));
await wait(500);
const shot=await cmd('Page.captureScreenshot',{format:'png'});
fs.writeFileSync('scratchpad/r248-vista.png', Buffer.from(shot.data,'base64'));
console.log('captura lista');
ws.close();
